// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Greet: typeof import('./src/components/Greet.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TC: typeof import('tdesign-vue-next')['C']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCol: typeof import('tdesign-vue-next')['Col']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TRow: typeof import('tdesign-vue-next')['Row']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}
